---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: dep1
  name: nft-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dep1
    spec:
      containers:
      - image: abhaypande/nft-store
        name: nft-store-container
---
---
apiVersion: v1
kind: Service
metadata:
  name: nft-store
spec:
  selector:
    app: dep1
  ports:
  - nodePort: 30000
    port: 8082
    targetPort: 8888
  type: NodePort
